name = "SWS Timeless"
author = "Maid"
prefix = "swst"
mainprefix = "x"

[hemtt.launch.default]
workshop = [
    "463939057", # ace
    "450814997", # cba_a3

    # tools
    "2369477168", # advanced developer tools
]

[hemtt.launch.patch]
workshop = [
    "463939057", # ace
    "450814997", # cba_a3

    # optionals
    "2522638637", # ace arsenal extended
    "2369477168", # advanced developer tools
]

[hemtt.release]
archive = false

[files]
exclude = ["*.inc"]
